USE [cv_db]
GO
/****** Object:  Table [dbo].[areaAziendale_LOOKUP]    Script Date: 08/29/2018 15:02:00 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[areaAziendale_LOOKUP](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nomeArea] [varchar](150) NOT NULL,
 CONSTRAINT [pk_areaAziendale] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
